import type { Config } from "tailwindcss"

const config: Config = {
  darkMode: ["class"],
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "*.{js,ts,jsx,tsx,mdx}",
    "app/**/*.{ts,tsx}",
    "components/**/*.{ts,tsx}",
    "*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        // Luxury romantic palette
        burgundy: {
          50: "#FFF8F8",
          100: "#FFE8E8",
          200: "#FFD1D1",
          300: "#FFB3B3",
          400: "#FF8A8A",
          500: "#FF5C5C",
          600: "#E63946",
          700: "#C62828",
          800: "#9A1B1B",
          900: "#4A0E2F",
        },
        blush: {
          50: "#FFF8F8",
          100: "#FFEEF0",
          200: "#FFDDE2",
          300: "#FFC2CC",
          400: "#FF9FB0",
          500: "#F8B7CC",
          600: "#E091A3",
          700: "#C86B7A",
          800: "#B04551",
          900: "#982028",
        },
        gold: {
          50: "#FFFEF7",
          100: "#FFFAEB",
          200: "#FFF2C7",
          300: "#FFE699",
          400: "#FFD666",
          500: "#D4A017",
          600: "#B8860B",
          700: "#9A6F08",
          800: "#7C5806",
          900: "#5E4104",
        },
        ivory: {
          50: "#FFFFFF",
          100: "#FFF8E7",
          200: "#FFF0CF",
          300: "#FFE8B7",
          400: "#FFE09F",
          500: "#FFD887",
          600: "#E6C26F",
          700: "#CCAC57",
          800: "#B3963F",
          900: "#998027",
        },
        quartz: {
          50: "#FFFAFA",
          100: "#FFF0F0",
          200: "#FFE1E1",
          300: "#FFD2D2",
          400: "#FFC3C3",
          500: "#F7CAC9",
          600: "#DEB5B4",
          700: "#C5A09F",
          800: "#AC8B8A",
          900: "#937675",
        },
        lavender: {
          50: "#FDFAFD",
          100: "#FAF0FA",
          200: "#F5E1F5",
          300: "#F0D2F0",
          400: "#EBC3EB",
          500: "#D8BFD8",
          600: "#C2ABC2",
          700: "#AC97AC",
          800: "#968396",
          900: "#806F80",
        },
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
      },
      fontFamily: {
        cursive: ["var(--font-cursive)", "Dancing Script", "cursive"],
        serif: ["var(--font-serif)", "Playfair Display", "serif"],
        elegant: ["Great Vibes", "cursive"],
        body: ["Lora", "serif"],
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      animation: {
        "luxury-heartbeat": "luxury-heartbeat 0.8s ease infinite",
        "floating-luxury": "floating-luxury 4s ease-in-out infinite",
        "romantic-pulse": "romantic-pulse 3s infinite alternate",
        typewriter: "typewriter 3s steps(40, end)",
        flicker: "flicker 1.5s ease-in-out infinite",
        "heart-burst": "heartBurst 1s ease-out forwards",
        "heart-float": "heartFloat 3s ease-out forwards",
        sparkle: "sparkle 2s linear infinite",
        twinkle: "twinkle 3s ease-in-out infinite",
        drift: "drift 5s ease-in-out infinite",
        "slide-in": "slideIn 0.5s ease-out",
        "heart-pop": "heartPop 0.6s ease-out",
        "fade-in": "fadeIn 0.5s ease-out",
      },
      boxShadow: {
        luxury: "0 8px 20px rgba(74, 14, 47, 0.3)",
        "gold-glow": "0 0 15px rgba(212, 160, 23, 0.5)",
        "blush-glow": "0 0 20px rgba(248, 183, 204, 0.6)",
        velvet: "0 10px 20px rgba(0, 0, 0, 0.4)",
      },
      backgroundImage: {
        "starry-night": "linear-gradient(180deg, #1C2526, #4A0E2F)",
        "luxury-gradient": "linear-gradient(135deg, #F8B7CC, #FFF8E7)",
        "velvet-texture": "linear-gradient(135deg, #4A0E2F, #6B1A44)",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
}

export default config
